//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWApi01
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusinessUser
    {
        public tblBusinessUser()
        {
            this.tblServices = new HashSet<tblService>();
        }
    
        public int BusinessUserID { get; set; }
        public bool UserType { get; set; }
        public string UserName { get; set; }
        public string UserContact { get; set; }
        public string UserAddress { get; set; }
        public System.DateTime EntryDate { get; set; }
        public long Business_ID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> DeActiveDate { get; set; }
        public string ImagePath { get; set; }
    
        public virtual tblBusiness tblBusiness { get; set; }
        public virtual ICollection<tblService> tblServices { get; set; }
    }
}
