//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWApi01
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblService
    {
        public long ServiceID { get; set; }
        public int LocalServiceID { get; set; }
        public string ServiceType { get; set; }
        public string VehicleType { get; set; }
        public string VehicleMake { get; set; }
        public string Party { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleReg { get; set; }
        public decimal Commision { get; set; }
        public decimal Amount { get; set; }
        public string CustomerName { get; set; }
        public string Contact { get; set; }
        public string Comments { get; set; }
        public System.DateTime CurrentDate { get; set; }
        public System.DateTime CurrentTime { get; set; }
        public int BusinessUser_ID { get; set; }
    
        public virtual tblBusinessUser tblBusinessUser { get; set; }
    }
}
